# ==============================================================================
# ACEDIA-SHELL
# Minimal Hyprlock
# ==============================================================================


# ==============================================================================
# GENERAL
# ==============================================================================

general {
    hide_cursor = true
    ignore_empty_input = false
    immediate_render = true
    text_trim = true
    fractional_scaling = 2

    fail_timeout = 2000
}


# ==============================================================================
# AUTHENTICATION
# ==============================================================================

auth {
    pam:enabled = true
    pam:module = hyprlock
}


# ==============================================================================
# BACKGROUND
# ==============================================================================

background {
    monitor =

    path = screenshot

    blur_passes = 2
    blur_size = 6

    noise = 0.01

    contrast = 0.90
    brightness = 0.70
    vibrancy = 0.08
    vibrancy_darkness = 0.05

    zindex = -1
}


# ==============================================================================
# DATE
# ==============================================================================

label {
    monitor =

    text = cmd[update:60000] date "+%A, %B %d"

    color = #A6A1B8

    font_size = 14
    font_family = JetBrainsMono Nerd Font

    halign = center
    valign = center

    position = 0, 125

    zindex = 1
}


# ==============================================================================
# PROFILE
# ==============================================================================

image {
    monitor =

    path = ~/.face

    size = 96

    border_size = 2
    border_color = #B9A7FF

    rounding = -1

    position = 0, 25

    halign = center
    valign = center

    shadow_passes = 2
    shadow_size = 6
    shadow_color = rgba(0, 0, 0, 0.40)

    zindex = 1
}


label {
    monitor =

    text = $USER

    color = #F0EDF7

    font_size = 14
    font_family = JetBrainsMono Nerd Font

    position = 0, -50

    halign = center
    valign = center

    zindex = 1
}


# ==============================================================================
# PASSWORD
# ==============================================================================

input-field {
    monitor =

    size = 300, 52

    outline_thickness = 2
    rounding = 17

    outer_color = #B9A7FF
    inner_color = #211F2A

    font_color = #F0EDF7
    font_family = JetBrainsMono Nerd Font

    dots_size = 0.25
    dots_spacing = 0.18
    dots_center = true
    dots_rounding = -1

    fade_on_empty = false

    placeholder_text = Password

    check_color = #B9A7FF
    fail_color = #FF6B6B

    fail_text = $FAIL

    capslock_color = #D9B8FF

    position = 0, -115

    halign = center
    valign = center

    shadow_passes = 2
    shadow_size = 7
    shadow_color = rgba(0, 0, 0, 0.40)

    zindex = 2
}