# Auto-generated by Matugen.
# Do not edit manually.

export ACEDIA_COLOR_BACKGROUND="{{ colors.background.default.hex }}"
export ACEDIA_COLOR_SURFACE="{{ colors.surface.default.hex }}"
export ACEDIA_COLOR_SURFACE_VARIANT="{{ colors.surface_variant.default.hex }}"

export ACEDIA_COLOR_PRIMARY="{{ colors.primary.default.hex }}"
export ACEDIA_COLOR_PRIMARY_CONTAINER="{{ colors.primary_container.default.hex }}"
export ACEDIA_COLOR_ON_PRIMARY="{{ colors.on_primary.default.hex }}"

export ACEDIA_COLOR_SECONDARY="{{ colors.secondary.default.hex }}"
export ACEDIA_COLOR_SECONDARY_CONTAINER="{{ colors.secondary_container.default.hex }}"
export ACEDIA_COLOR_ON_SECONDARY="{{ colors.on_secondary.default.hex }}"

export ACEDIA_COLOR_TERTIARY="{{ colors.tertiary.default.hex }}"
export ACEDIA_COLOR_TERTIARY_CONTAINER="{{ colors.tertiary_container.default.hex }}"

export ACEDIA_COLOR_TEXT="{{ colors.on_background.default.hex }}"
export ACEDIA_COLOR_TEXT_MUTED="{{ colors.on_surface_variant.default.hex }}"
export ACEDIA_COLOR_BORDER="{{ colors.outline.default.hex }}"

export ACEDIA_COLOR_ERROR="{{ colors.error.default.hex }}"
export ACEDIA_COLOR_ON_ERROR="{{ colors.on_error.default.hex }}"
